### ISSUE TITLE
rendererConfig#path should support a TypeScript Vite config

### ISSUE THREAD

**Issue by alii** [Kiyozz/electron-esbuild#22]
Right now the following configuration will not work:
```yml
rendererConfig:
  type: vite
  path: src/renderer/vite.config.ts
  src: src/renderer/main.ts
  output: dist/renderer
```

```ts
// src/renderer/vite.config.ts
import {defineConfig} from 'vite';
import reactRefresh from '@vitejs/plugin-react-refresh';

export default defineConfig({
	plugins: [reactRefresh()],
	build: {
		target: 'chrome89',
	},
});
```
![image](https://user-images.githubusercontent.com/25351731/125198845-8bc86700-e25b-11eb-8f22-dfaf5d80f0be.png)
